# Generated by Django 4.0.6 on 2022-07-31 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcards', '0003_cardscategories_delete_postcategories_and_more'),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AddField(
            model_name='basket',
            name='full_price',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_price', to='foodcards.cards'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='list_food',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='foodcards.cards'),
        ),
    ]
