# Generated by Django 4.0.6 on 2022-07-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Категория поста',
                'verbose_name_plural': 'Категории постов',
            },
        ),
        migrations.AlterField(
            model_name='cards',
            name='image',
            field=models.ImageField(blank=True, help_text='An image or logo for this Card (optional)', null=True, upload_to=''),
        ),
        migrations.AlterModelTable(
            name='cards',
            table='cards_db',
        ),
    ]
