# Generated by Django 4.0.6 on 2022-07-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcards', '0005_alter_cards_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardscategories',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
